# Generated by Django 5.1.3 on 2024-11-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
